import assert from 'node:assert/strict';
import {onRequest} from '../functions/api/receipt.js';
import {calculate} from '../dist/calc.mjs';
const image={mimeType:'image/jpeg',data:'/9j/AAAAAAAAAAAA',mode:'standard'};
const png={mimeType:'image/png',data:'iVBORw0KGgoAAAAA'};
const segmented={images:[{mimeType:image.mimeType,data:image.data},png],mode:'standard'};
const req=(body=image,origin='https://test.pages.dev')=>new Request('https://test.pages.dev/api/receipt',{method:'POST',headers:{Origin:origin,'Content-Type':'application/json'},body:JSON.stringify(body)});
const env={GEMINI_API_KEY:'test-secret-only'};
assert.equal((await onRequest({request:req(),env:{}})).status,503);
assert.equal((await onRequest({request:req(image,'https://other.test'),env})).status,403);
assert.equal((await onRequest({request:req({...image,data:'AAAAAAAAAAAAAAAA'}),env})).status,400);
assert.equal((await onRequest({request:req({images:Array(7).fill({mimeType:image.mimeType,data:image.data}),mode:'standard'}),env})).status,400);
const receipt={currency:'CHF',items:[{name:'2 Latte',price:9},{name:'Kola',price:5},{name:'Schnitzel',price:22},{name:'Spatzli',price:18.5}],tax:0,service:0,discount:0,total:54.5,needsReview:false};
let requestBody,requestUrl;globalThis.fetch=async(url,opts)=>{requestUrl=url;assert.equal(opts.headers['x-goog-api-key'],'test-secret-only');assert.equal(opts.headers['Api-Revision'],'2026-05-20');requestBody=JSON.parse(opts.body);assert.equal(requestBody.response_format.type,'text');assert.equal(requestBody.response_format.mime_type,'application/json');assert.equal(requestBody.response_format.schema,undefined);assert.equal(requestBody.store,false);return Response.json({status:'completed',steps:[{type:'model_output',content:[{type:'text',text:JSON.stringify(receipt)}]}]})};
let response=await onRequest({request:req(segmented),env});assert.equal(response.status,200);assert.deepEqual((await response.json()).receipt,receipt);assert.ok(requestUrl.endsWith('/v1beta/interactions'));assert.equal(requestBody.model,'gemini-3.5-flash-lite');assert.equal(requestBody.input.filter(x=>x.type==='image').length,2);assert.equal(requestBody.input[1].mime_type,'image/jpeg');assert.equal(requestBody.input[2].mime_type,'image/png');assert.match(requestBody.input[0].text,/segments/i);
response=await onRequest({request:req(),env});assert.equal(response.status,200);assert.equal(requestBody.input.filter(x=>x.type==='image').length,1);
await onRequest({request:req({...segmented,mode:'careful'}),env});assert.equal(requestBody.model,'gemini-3.8-flash');
receipt.items[0].price=null;response=await onRequest({request:req(segmented),env});assert.equal((await response.json()).receipt.needsReview,true);
receipt.items[0].price=-1;assert.equal((await onRequest({request:req(segmented),env})).status,422);
globalThis.fetch=async()=>new Response('{}',{status:429});assert.equal((await onRequest({request:req(segmented),env})).status,429);
globalThis.fetch=async()=>{throw Error('test-secret-only')};response=await onRequest({request:req(segmented),env});assert.ok(!(await response.text()).includes('test-secret-only'));
const p=[{id:'a'},{id:'b'},{id:'c'}];const c=calculate(p,[{name:'Shared bill',price:5450,owners:['a','b','c']}],0,0,0);assert.deepEqual(c.shares,[1817,1817,1816]);assert.equal(c.shares.reduce((a,b)=>a+b,0),5450);
console.log('PASS: request validation, secret isolation, segmented Interactions payload, model selection, null prices, provider errors, cent rounding.');
